/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab08;

import java.util.StringTokenizer;
import javax.swing.JFrame;
import javax.swing.JLabel;
import sun.util.locale.StringTokenIterator;

/**
 *
 * @author rodrigo
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();

        setTitle("Calculadora");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("7");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("8");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("+");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("1");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("2");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("3");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("*");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("0");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setText("=");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("/");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel1.setText("=");

        jButton16.setText("C");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton15)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void calc(){
        try{
            StringTokenizer st = new StringTokenizer(jTextField1.getText());
            int A = Integer.parseInt(st.nextToken());
            char sel = st.nextToken().charAt(0);
            if (sel != '/' && sel != '*' && sel != '-' && sel !='+'){
                throw new ArithmeticException("Operador não esperado.");
            }
            int B = Integer.parseInt(st.nextToken());
            float R = 0;

            switch(sel){
                case '/':
                    R = (float)(A)/B; break;
                case '*':
                    R = A*B; break;
                case '+':
                    R = A+B; break;
                case '-':
                    R = A-B; break;
            }

            jTextField2.setText(""+R);

        }catch(Exception e){
            JFrame janela = new JFrame("Mensagem de erro");
            JLabel erro = new JLabel(""+e);
            janela.add(erro);
            janela.setLocationRelativeTo(null);
            janela.setSize(erro.getMinimumSize());
            janela.setVisible(true);
        }
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        calc();
    }

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        calc();
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 7_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="7";
            else s+=" 7";
        }else s+=" 7";
        jTextField1.setText(s);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 8_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="8";
            else s+=" 8";
        }else s+=" 8";
        jTextField1.setText(s);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 9_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="9";
            else s+=" 9";
        }else s+=" 9";
        jTextField1.setText(s);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO +_key:
        String s = jTextField1.getText();
        if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+=" +";
        jTextField1.setText(s);
    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 4_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="4";
            else s+=" 4";
        }else s+=" 4";
        jTextField1.setText(s);
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 5_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="5";
            else s+=" 5";
        }else s+=" 5";
        jTextField1.setText(s);
    }

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 6_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="6";
            else s+=" 6";
        }else s+=" 6";
        jTextField1.setText(s);
    }

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO -_key:
        String s = jTextField1.getText();
        if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+=" -";
        jTextField1.setText(s);
    }

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 1_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="1";
            else s+=" 1";
        }else s+=" 1";
        jTextField1.setText(s);
    }

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 2_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="2";
            else s+=" 2";
        }else s+=" 2";
        jTextField1.setText(s);
    }

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 3_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="3";
            else s+=" 3";
        }else s+=" 3";
        jTextField1.setText(s);
    }

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO *_key:
        String s = jTextField1.getText();
        if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+=" *";
        jTextField1.setText(s);
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO 0_key:
        String s = jTextField1.getText();
        if(s.length()>0)
        {
            if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+="0";
            else s+=" 0";
        }else s+=" 0";
        jTextField1.setText(s);
    }

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO /_key:
        String s = jTextField1.getText();
        if(s.charAt(s.length()-1) > '0' && s.charAt(s.length()-1) < '9') s+=" /";
        jTextField1.setText(s);
    }

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration
}
